name: Bump NPM Version


inputs:
  bump:
    description: 'Which version bump (patch, minor, major)'
    required: true
  token:
    description: 'GitHub token for authentication'
    required: true
  repository:
    description: 'GitHub repository to push changes to'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Configure Git
      shell: bash
      run: |
        git config user.name 'celobot'
        git config user.email 'github-celobot@celonis.com'
        git remote set-url origin https://x-access-token:${{ inputs.token }}@github.com/${{ inputs.repository }}

    - name: Run npm version
      shell: bash
      run: |
        npm install
        npm version ${{ inputs.bump }} -m "chore: bump version to %s"
        git push origin HEAD
        git push origin --tags
