name: Build and publish Workflow

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'package.json'
      - '.github/**'
jobs:
  build:
    runs-on: ubuntu-latest
    name: Npm install and npm build

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node with Github Registry
        uses: actions/setup-node@v1
        with:
          node-version: '20'
          registry-url: https://npm.pkg.github.com/celonis
          scope: '@celonis'

      - name: Yarn Install
        run: yarn install

      - name: Yarn Build
        run: yarn build

      - name: Yarn Test
        run: yarn test

      - name: Move files to build
        run: |
          cp README.md dist/README.md
          cp LICENSE dist/LICENSE

      - name: Publish to Github Registry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cd dist/ && npm publish

      - name: Setup publish to Npm Registry
        uses: actions/setup-node@v1
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/
          scope: '@celonis'

      - name: Publish to Npm Registry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: cd dist/ && npm publish --access public

      - uses: actions/checkout@master
        name: Checkout Master
        with:
          fetch-depth: '0'

      - name: Bump minor version
        run: |
          CURRENT_VERSION=$(jq -r .version package.json)
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
          NEW_MINOR=$((MINOR + 1))
          NEW_VERSION="$MAJOR.$NEW_MINOR.0"
          echo "Bumping version: $CURRENT_VERSION -> $NEW_VERSION"
          jq ".version = \"$NEW_VERSION\"" package.json > temp.json && mv temp.json package.json

      - name: Push version bump
        shell: bash
        run: |
          git config user.name 'celobot'
          git config user.email 'github-celobot@celonis.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          
          git add package.json
          git commit -m "Version bump to $NEW_VERSION"
          git push -u origin master
