name: Build and publish Workflow

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'package.json'
      - '.github/**'
jobs:
  build:
    runs-on: ubuntu-latest
    name: Npm install and npm build

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node with Github Registry
        uses: actions/setup-node@v1
        with:
          node-version: '10.17.0'
          registry-url: https://npm.pkg.github.com/celonis
          scope: '@celonis'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Yarn Install
        run: yarn install

      - name: Yarn Build
        run: yarn build

      - name: Move files to build
        run: |
          cp package.json dist/package.json
          cp README.md dist/README.md
          cp LICENSE dist/LICENSE

      - name: Publish to Github Registry
        run: cd dist/ && npm publish

      - name: Setup publish to Npm Registry
        uses: actions/setup-node@v1
        with:
          node-version: '10.17.0'
          registry-url: https://registry.npmjs.org/
          scope: '@celonis'
          token: ${{ secrets.NPM_TOKEN }}

      - name: Publish to Npm Registry
        run: npm publish --access public

      - uses: actions/checkout@master
        name: Checkout Master
        with:
          fetch-depth: '0'

      - uses: tool3/bump@v1
        name: Bump patch version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
