name: Build and Publish Workflow

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node with GitHub Registry
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: https://npm.pkg.github.com/celonis
          scope: '@celonis'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Project
        run: yarn build

      - name: Run Tests
        run: yarn test

      - name: Move files to dist
        run: |
          cp README.md dist/README.md
          cp LICENSE dist/LICENSE

      - name: Check if last commit is a version bump
        id: check_version_bump
        run: |
          last_commit_message=$(git log -1 --pretty=%B)
          echo "Last commit message: $last_commit_message"

          if [[ "$last_commit_message" =~ "[Release]: Bump version" ]]; then
            echo "is_bump=true" >> $GITHUB_OUTPUT
          else
            echo "is_bump=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload Build Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 1

    outputs:
      is_bump: ${{ steps.check_version_bump.outputs.is_bump }}

  publish:
    name: Publish to Registries
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.outputs.is_bump == 'true'

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Setup Node for GitHub Registry
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: https://npm.pkg.github.com/celonis
          scope: '@celonis'

      - name: Publish to GitHub Registry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd dist/
          npm publish

      - name: Setup Node for NPM Registry
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: https://registry.npmjs.org/
          scope: '@celonis'

      - name: Publish to NPM Registry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd dist/
          npm publish --access public
